trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self

variables:
- name: GCR_PATH
  value: GCR_PATH
- name: TAG
  value: latest
# - group: PipelineVariables

stages: 
- stage: DockerBuildValidatePush
  displayName: Build Test Push
  jobs:
    - deployment: DeployImageToGCR
      displayName: Build Test Push
      environment: 'trivy'
      pool:
        vmImage: 'ubuntu-latest' # Set value in Azure Dev Ops Build Pipeline
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadSecureFile@1
              name: Google_Credentials
              displayName: 'Download Google GCR Credentials'
              inputs:
                secureFile: 'google_service_auth.json'
            - script: |
                gcloud auth activate-service-account --key-file $(Google_Credentials.secureFilePath) --quiet
                gcloud auth configure-docker "gcr.io" --quiet

            - task: ShellScript@2
              inputs:
                scriptPath: ./builtin-db.sh
                args: $(GCR_PATH) $(TAG)
              displayName: 'Publish To GCR'