apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: https://github.com/jorgyp/trivy
    - title: Documentation
      url: https://github.com/jorgyp/trivy/docs
  annotations:
    github.com/project-slug: jorgyp/trivy
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
