FROM aquasec/trivy

RUN chmod 777 /usr/local/bin/trivy
RUN mkdir -p /root/.cache && trivy --download-db-only --cache-dir /root/.cache/
RUN mkdir -p /var/lib/trivy && trivy --download-db-only --cache-dir /var/lib/trivy

RUN chmod 777 -R /var/lib/trivy/

RUN adduser -D user
USER user
ENTRYPOINT ["trivy"]
